export enum EnvFields {
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  RUN_MIGRATIONS = 'RUN_MIGRATIONS',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_SECRET = 'GOOGLE_SECRET',

  HOST = 'HOST',
  PORT = 'PORT',
  MODE = 'MODE',
  USE_SSL = 'USE_SSL',
  SESSION_SECRET = 'SESSION_SECRET',
}
