export enum EnvFields {
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  RUN_MIGRATIONS = 'RUN_MIGRATIONS',

  HOST = 'HOST',
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
}
